targets:
  $default:
    sources:
      - lib/**
      - github.schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: github.schema.graphql
              queries_glob: lib/graphql/search_repositories.graphql
              output: lib/graphql/search_repositories.dart
